const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs/promises');
const path = require('path');

const root = path.join(__dirname, '..');

async function readJson(name) {
  return JSON.parse(await fs.readFile(path.join(root, name), 'utf8'));
}

test('electron updater and publish metadata are configured without renderer version literals', async () => {
  const pkg = await readJson('package.json');
  assert.ok(pkg.dependencies['electron-updater']);
  assert.equal(pkg.build.productName, 'VANTA');
  assert.deepEqual(pkg.build.win.target, [{ target: 'nsis', arch: ['x64'] }]);
  assert.deepEqual(pkg.build.linux.target, [{ target: 'AppImage', arch: ['x64'] }]);
  assert.equal(pkg.build.publish[0].provider, 'github');
  assert.equal(pkg.build.win.publish[0], 'github');
  assert.equal(pkg.build.linux.publish[0], 'github');
  assert.equal(pkg.build.nsis.createDesktopShortcut, false);
  assert.equal(pkg.build.nsis.include, 'build/installer/desktop-shortcut.nsh');

  const settings = await fs.readFile(path.join(root, 'renderer/settings-page.js'), 'utf8');
  assert.doesNotMatch(settings, /const APP_VERSION\s*=/);
  assert.match(settings, /state\.data\.appVersion/);
});

test('package builds do not publish implicitly while release builds publish explicitly', async () => {
  const pkg = await readJson('package.json');
  for (const script of ['build', 'build:win', 'build:win:linux-smoke', 'build:linux', 'build:local']) {
    assert.match(pkg.scripts[script], /--publish never(?:\s|$)/, `${script} must not publish from CI`);
  }
  assert.match(pkg.scripts['release:win'], /--publish always(?:\s|$)/);
  assert.match(pkg.scripts['release:linux'], /--publish always(?:\s|$)/);
});

test('generated updater metadata matches the current release when current-version artifacts exist', async () => {
  const pkg = await readJson('package.json');
  for (const name of ['latest.yml', 'latest-linux.yml']) {
    const artifact = name === 'latest.yml' ? `VANTA-Setup-${pkg.version}.exe` : `VANTA-${pkg.version}.AppImage`;
    const artifactPath = path.join(root, 'dist', artifact);
    try { await fs.access(artifactPath); } catch (error) {
      if (error.code === 'ENOENT') continue;
      throw error;
    }
    const file = path.join(root, 'dist', name);
    try {
      const content = await fs.readFile(file, 'utf8');
      assert.match(content, new RegExp(`^version: ${pkg.version}$`, 'm'));
      assert.match(content, /sha512:\s+\S+/);
      assert.match(content, /path:\s+\S+/);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
      assert.ok(true, `${name} is generated by release build`);
    }
  }
});

test('update IPC event names remain explicit and renderer does not import updater internals', async () => {
  const main = await fs.readFile(path.join(root, 'src/main/index.js'), 'utf8');
  const preload = await fs.readFile(path.join(root, 'src/main/preload.js'), 'utf8');
  const renderer = await fs.readFile(path.join(root, 'renderer/app.js'), 'utf8');
  assert.match(main, /register\('update:check'/);
  assert.match(main, /register\('update:download'/);
  assert.match(main, /register\('update:install'/);
  assert.match(preload, /onUpdateEvent/);
  assert.match(preload, /update:event/);
  assert.doesNotMatch(renderer, /electron-updater/);
});
