const FULL_TEXT = {
  ru: { Home: 'Главная', Mods: 'Моды', Library: 'Библиотека', Authors: 'Авторы', Settings: 'Настройки', Heroes: 'Герои', World: 'Мир', Interface: 'Интерфейс', Effects: 'Эффекты', Other: 'Другое', 'Install mod': 'Установить', Installed: 'Установлено', Uninstall: 'Удалить', Remove: 'Удалить', Update: 'Обновить', 'All mods': 'Все моды', 'Loading catalog': 'Загрузка каталога', 'Choose a hero': 'Выберите героя', 'Search heroes': 'Поиск героев', Popular: 'Популярные', Default: 'По умолчанию', All: 'Все', Strength: 'Сила', Agility: 'Ловкость', Intelligence: 'Интеллект', Universal: 'Универсальные', 'Merge mods': 'Объединить моды', 'Enable selected': 'Включить выбранные', 'Disable selected': 'Выключить выбранные', 'Remove selected': 'Удалить выбранные', 'Select all': 'Выбрать всё', 'Create pack': 'Создать пак', 'Pack name': 'Название пака', 'No mods found': 'Моды не найдены', 'Catalog unavailable': 'Каталог недоступен' },
  en: { 'Установить': 'Install mod', 'Установлено': 'Installed', 'Удалить': 'Remove', 'Главная': 'Home', 'Моды': 'Mods', 'Библиотека': 'Library', 'Авторы': 'Authors', 'Настройки': 'Settings', 'Герои': 'Heroes', 'Мир': 'World', 'Интерфейс': 'Interface', 'Эффекты': 'Effects', 'Другое': 'Other', 'Выберите героя': 'Choose a hero', 'Поиск героев': 'Search heroes', 'Популярные': 'Popular', 'По умолчанию': 'Default', 'Все': 'All', 'Сила': 'Strength', 'Ловкость': 'Agility', 'Интеллект': 'Intelligence', 'Универсальные': 'Universal', 'Объединить моды': 'Merge mods', 'Включить выбранные': 'Enable selected', 'Выключить выбранные': 'Disable selected', 'Удалить выбранные': 'Remove selected', 'Выбрать всё': 'Select all', 'Создать пак': 'Create pack', 'Название пака': 'Pack name', 'Моды не найдены': 'No mods found', 'Каталог недоступен': 'Catalog unavailable' },
};
Object.assign(FULL_TEXT.ru, {
  'Auto detect': 'Определить автоматически', Browse: 'Выбрать папку', 'Catalog source': 'Источник каталога', 'Dota 2 installation': 'Путь к Dota 2', 'Language folder': 'Папка языка', 'Application language': 'Язык интерфейса', 'Stored independently in VANTA': 'Язык интерфейса VANTA', 'Auto update': 'Автообновление', 'Check for VANTA updates when available': 'Проверять обновления VANTA', 'Interface scale': 'Масштаб интерфейса', 'Adjust density for your display': 'Настройка плотности интерфейса', 'Discord activity': 'Активность в Discord', 'Show VANTA activity in Discord': 'Показывать активность VANTA в Discord', 'Refresh catalog': 'Обновить каталог', Reset: 'Сбросить', 'Social networks': 'Социальные сети', 'Project news and support': 'Новости и поддержка проекта', 'Mods folder': 'Папка модов', Guides: 'Гайды', 'Loading catalog': 'Загрузка каталога', 'Catalog unavailable': 'Каталог недоступен', 'Nothing here yet': 'Пока ничего нет', 'Try another search or category.': 'Попробуйте другой поиск или категорию.', 'Choose a hero': 'Выберите героя', 'Browse cosmetic mods by hero, then narrow them down by slot.': 'Просматривайте косметические моды героя и фильтруйте их по слоту.', 'All slots': 'Все слоты', 'Search this hero\'s mods': 'Поиск модов героя', 'English': 'Английский', Russian: 'Русский', 'Simplified Chinese': 'Китайский (упрощённый)'
});
Object.assign(FULL_TEXT.en, {
  'Определить автоматически': 'Auto detect', 'Выбрать папку': 'Browse', 'Источник каталога': 'Catalog source', 'Путь к Dota 2': 'Dota 2 installation', 'Папка языка': 'Language folder', 'Язык интерфейса': 'Application language', 'Язык интерфейса VANTA': 'Stored independently in VANTA', Автообновление: 'Auto update', 'Проверять обновления VANTA': 'Check for VANTA updates when available', 'Масштаб интерфейса': 'Interface scale', 'Настройка плотности интерфейса': 'Adjust density for your display', 'Активность в Discord': 'Discord activity', 'Показывать активность VANTA в Discord': 'Show VANTA activity in Discord', 'Обновить каталог': 'Refresh catalog', Сбросить: 'Reset', 'Социальные сети': 'Social networks', 'Новости и поддержка проекта': 'Project news and support', 'Папка модов': 'Mods folder', Гайды: 'Guides', 'Загрузка каталога': 'Loading catalog', 'Каталог недоступен': 'Catalog unavailable', 'Пока ничего нет': 'Nothing here yet', 'Попробуйте другой поиск или категорию.': 'Try another search or category.', 'Выберите героя': 'Choose a hero', 'Просматривайте косметические моды героя и фильтруйте их по слоту.': 'Browse cosmetic mods by hero, then narrow them down by slot.', 'Все слоты': 'All slots', 'Поиск модов героя': "Search this hero's mods", Английский: 'English', Русский: 'Russian', 'Китайский (упрощённый)': 'Simplified Chinese'
});
Object.assign(FULL_TEXT.ru, {
  'HERO POPULARITY': 'ПОПУЛЯРНОСТЬ ГЕРОЯ', 'Total downloads': 'Скачивания', 'Popularity rank': 'Место по популярности', 'Catalog mods': 'Модов в каталоге', 'Hero catalog': 'Каталог героев', 'Browse cosmetic mods by hero, then narrow them down by slot.': 'Просматривайте косметические моды героев и фильтруйте их по слотам.', 'Hero loadout': 'Набор героя', 'Choose a slot to explore the available cosmetic mods.': 'Выберите слот, чтобы посмотреть доступные косметические моды.', 'Back to heroes': 'Назад к героям', 'Hero popularity': 'Популярность героя', 'Атрибуты': 'Атрибуты', 'Редкость': 'Редкость', 'Теги': 'Теги', 'Остальное': 'Остальное', 'Универсал': 'Универсальные', 'Аниме': 'Аниме', 'Недавно обновлённые': 'Недавно обновлённые', 'С большим количеством модов': 'С большим количеством модов'
});
Object.assign(FULL_TEXT.en, {
  'ПОПУЛЯРНОСТЬ ГЕРОЯ': 'HERO POPULARITY', 'Скачивания': 'Downloads', 'Место по популярности': 'Popularity rank', 'Модов в каталоге': 'Catalog mods', 'Каталог героев': 'Hero catalog', 'Просматривайте косметические моды героев и фильтруйте их по слотам.': 'Browse cosmetic mods by hero, then narrow them down by slot.', 'Набор героя': 'Hero loadout', 'Выберите слот, чтобы посмотреть доступные косметические моды.': 'Choose a slot to explore the available cosmetic mods.', 'Назад к героям': 'Back to heroes', 'Популярность героя': 'Hero popularity', 'Атрибуты': 'Attributes', 'Редкость': 'Rarity', 'Теги': 'Tags', 'Остальное': 'Other', 'Универсал': 'Universal', 'Аниме': 'Anime', 'Недавно обновлённые': 'Recently updated', 'С большим количеством модов': 'Most mods'
});
Object.assign(FULL_TEXT.ru, {
  Heroes: 'Герои', 'Hero items': 'Предметы героев', 'Hero effects': 'Эффекты героев', 'Hero sounds': 'Звуки героев', Terrains: 'Ландшафты', Trees: 'Деревья', River: 'Река', Creeps: 'Крипы', Towers: 'Башни', Roshan: 'Рошан', Ancients: 'Древние', Tormentor: 'Терминатор', Wards: 'Варды', Couriers: 'Курьеры', Pedestals: 'Пьедесталы', 'Deny creeps': 'Денай крипов', 'Menu backgrounds': 'Фоны меню', HUDs: 'HUD', Emblems: 'Эмблемы', 'Versus Screen': 'Versus Screen', 'Item icons': 'Иконки предметов', Ranks: 'Ранги', Pings: 'Сигналы', Cursors: 'Курсоры', Shaders: 'Шейдеры', 'Effect packs': 'Паки эффектов', 'Item effects': 'Эффекты предметов', 'Ranged attacks': 'Дальние атаки', 'High five': 'Дай пять', Packs: 'Версус скин', Optimization: 'Оптимизация', Other: 'Остальное', Sites: 'Сайты', Pack: 'Пак'
});
Object.assign(FULL_TEXT.en, {
  'Герои': 'Heroes', 'Предметы героев': 'Hero items', 'Эффекты героев': 'Hero effects', 'Звуки героев': 'Hero sounds', 'Ландшафты': 'Terrains', 'Деревья': 'Trees', 'Река': 'River', 'Крипы': 'Creeps', 'Башни': 'Towers', 'Рошан': 'Roshan', 'Древние': 'Ancients', 'Терминатор': 'Tormentor', 'Варды': 'Wards', 'Курьеры': 'Couriers', 'Пьедесталы': 'Pedestals', 'Денай крипов': 'Deny creeps', 'Фоны меню': 'Menu backgrounds', 'Эмблемы': 'Emblems', 'Иконки предметов': 'Item icons', 'Ранги': 'Ranks', 'Сигналы': 'Pings', 'Курсоры': 'Cursors', 'Шейдеры': 'Shaders', 'Паки эффектов': 'Effect packs', 'Эффекты предметов': 'Item effects', 'Дальние атаки': 'Ranged attacks', 'Дай пять': 'High five', 'Версус скин': 'Versus skin', 'Оптимизация': 'Optimization', 'Остальное': 'Other', 'Сайты': 'Sites', 'Пак': 'Pack'
});
function translateUi() {
  if (typeof state === 'undefined') return;
  const language = state.data?.settings?.appLanguage === 'ru' ? 'ru' : 'en';
  document.body.dataset.fullLanguage = language;
  const map = FULL_TEXT[language];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach((node) => { const value = node.nodeValue.trim(); if (map[value]) node.nodeValue = node.nodeValue.replace(value, map[value]); });
  document.querySelectorAll('input[placeholder]').forEach((input) => { if (language === 'ru' && input.placeholder === 'Search heroes') input.placeholder = 'Поиск героев'; if (language === 'en' && input.placeholder === 'Поиск героев') input.placeholder = 'Search heroes'; });
}
const fullI18nObserver = new MutationObserver(() => requestAnimationFrame(translateUi));
fullI18nObserver.observe(document.body, { childList: true, subtree: true });
setTimeout(translateUi, 0);
